#!/bin/bash
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
echo "--- Running ESLint ---"
pnpm run lint
if [[ "$?" != 0 ]]; then
    printf "\033[41m❌ ESLint Failed\033[0m\n"
    exit 1
fi

echo "--- Running Prettier ---"
pnpm prettier --write src/*
if [[ "$?" != 0 ]]; then
    printf "\033[41m❌ Prettier Failed\033[0m\n"
    exit 1
fi

printf "\033[32m✅ ESLint Passed and Prettier Formatted\033[0m\n"