"use strict"

module.exports = {
  ...require("./no-export-const-classname"),
  ...require("./no-localstorage-direct"),
  ...require("./no-banned-words"),
  ...require("./no-function-in-deps"),
  ...require("./no-vague-names"),
  ...require("./attributes-order"),
  ...require("./sdk-method-naming"),
  ...require("./no-throwaway-alias"),
  ...require("./no-zustand-types-in-store-file"),
  ...require("./input-value-naming"),
  ...require("./hook-naming-convention"),
  ...require("./handle-prefix-location"),
  ...require("./response-variable-naming"),
  ...require("./db-redis-verb-naming"),
  ...require("./no-process-env-non-null-assertion"),
  ...require("./arrow-fn-only-for-hooks"),
  ...require("./ts-ignore-dynamic-table-only"),
  ...require("./type-naming-prefix"),
  ...require("./one-liner-component-props-interface"),
  ...require("./no-type-export-in-action-or-component"),
  ...require("./imports-order"),
  // file name differs from the rule id ("envs-order") on purpose - see the header of vars-order.js
  ...require("./vars-order"),
  // same here - the rule id is "no-unused-envs", see the header of unused-declared-vars.js
  ...require("./unused-declared-vars"),
  ...require("./no-high-level-import"),
  ...require("./check-importers"),
  ...require("./no-cross-route-group-absolute-import"),
  ...require("./require-absolute-import-for-shared-folders"),
  ...require("./use-rls-supabase-client"),
  ...require("./function-body-own-line"),
  ...require("./console-log-line-number"),
  ...require("./no-redundant-return-parens"),
  ...require("./no-zustand-selector"),
  ...require("./zustand-state-setter-pairing"),
  ...require("./prefer-inline-zustand-setter"),
  ...require("./api-folder-requires-api-namespace"),
  ...require("./api-type-req-resp-suffix"),
  ...require("./no-req-json-catch"),
  ...require("./no-void-only-jsx-handler"),
  ...require("./no-handlers-variable"),
  ...require("./no-inner-component"),
  ...require("./arrow-parens-avoid"),
  ...require("./require-storybook-url"),
  ...require("./no-untranslated-ui-i18n"),
  ...require("./no-vague-error-msg"),
}
